MenuMakerPL/Controllers/RecipeController.cs
// ReSharper disable FieldCanBeMadeReadOnly.Local

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using Logger;
using MenuMakerBLL;
using MenuMakerDAL;
using MenuMakerPL.Controllers.ActionFilters;
using MenuMakerPL.Models;

namespace MenuMakerPL.Controllers
{
    /// <summary>
    ///     Recipe controller. Handles Recipes and their implementations
    ///     Uses its own DAOs instead of the parent DAO
    ///     Must be a registered user to access any content
    /// </summary>
    [RoleCheck(DefaultRedirect, StandardUser, PowerUser, Admin)]
    public class RecipeController : MMController
    {
        private IngredientImplementationDAO _ingredientImplementationDAO;
        private IngredientsDAO _ingredientsDAO;
        private RecipeDAO _recipeDAO;

        public RecipeController ()
        {
            var connection = ConfigurationManager.ConnectionStrings["MenuMaker"].ConnectionString;
            _ingredientsDAO = new IngredientsDAO(connection);
            _ingredientImplementationDAO = new IngredientImplementationDAO(connection);
            _recipeDAO = new RecipeDAO(connection);
        }

        /// <summary>
        ///     Landing page is View All Recipes
        /// </summary>
        /// <returns></returns>
        public ActionResult Index ()
        {
            return RedirectToAction("ViewAllRecipes");
        }

        /// <summary>
        ///     View all Recipes page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ViewAllRecipes ()
        {
            var recipes = new List<RecipePO>();
            //Return Variable
            ActionResult response;
            ViewBag.Message = TempData["Message"];

            try
            {
                //convert recipes to PO versions
                recipes.AddRange(_recipeDAO.ReadAllRecipes().Select(recipe => new RecipePO(recipe)));
            }
            catch (Exception e)
            {
                //Error occurred return to user with message
                WriteErrorToLog(e);
                ViewBag.Message = e.Data["Problem"];
            }
            finally
            {
                response = View(recipes);
            }

            return response;
        }

        /// <summary>
        ///     Create Recipe page, must be at least PowerUser
        /// </summary>
        /// <returns></returns>
        [HttpGet, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult CreateRecipe ()
        {
            //Return variable
            ActionResult response = View();

            return response;
        }

        /// <summary>
        ///     Creates recipe with basic details, no ingredients and redirects to UpdateRecipe
        /// </summary>
        /// <param name="recipePO">recipe that will be created</param>
        /// <returns>Redirects to UpdateRecipe</returns>
        [HttpPost, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult CreateRecipe (RecipePO recipePO)
        {
            //Return variable
            ActionResult response;
            if (ModelState.IsValid)
                try
                {
                    //Generate recipe and get back ID
                    response = RedirectToAction("UpdateRecipe", _recipeDAO.CreateRecipe(recipePO));
                }
                catch (Exception e)
                {
                    //Error occurred, return page with message
                    WriteErrorToLog(e);
                    ViewBag.Message = e.Data["Problem"];
                    response = View(recipePO);
                }
            else //ModelState is not valid
                response = View(recipePO);

            return response;
        }

        /// <summary>
        ///     Views single recipe with details  by ID.
        /// </summary>
        /// <param name="recipeID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ViewRecipe (int recipeID)
        {
            //Return variable
            ActionResult response;

            try
            {
                var recipePO = new RecipePO(_recipeDAO.ReadRecipe(recipeID));
                var ingredients = _ingredientImplementationDAO.ReadRecipeIngredients(recipeID);
                var cost = IngredientImplementationBLO.SumIngredientsCost(ingredients);

                //Construct VM from ingredients, recipe, and cost
                var recipeVM = new FullRecipeVM(recipePO, ingredients, cost);
                ViewBag.Message = TempData["Message"];
                response = View(recipeVM);
            }
            catch (Exception e)
            {
                //Error occurred, return view with message
                WriteErrorToLog(e);
                TempData["Message"] = e.Data["Problem"];
                response = RedirectToAction("ViewAllRecipes");
            }

            return response;
        }

        /// <summary>
        ///     Update recipe page, constructed of many partial views using ajax
        /// </summary>
        /// <param name="recipeID">ID of recipe to be updated</param>
        /// <returns></returns>
        [HttpGet, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult UpdateRecipe (int recipeID)
        {
            //Return variable
            ActionResult response;

            try
            {
                var recipePO = new RecipePO(_recipeDAO.ReadRecipe(recipeID));
                var ingredients = _ingredientImplementationDAO.ReadRecipeIngredients(recipeID);
                response = View(new FullRecipeVM(recipePO, ingredients));
            }
            catch (Exception e)
            {
                //Error occurred, return with message.
                WriteErrorToLog(e);
                ViewBag.Message = e.Data["Problem"];
                response = View(new FullRecipeVM());
            }

            return response;
        }

        /// <summary>
        ///     Delete recipe by id, db should handle cascades. Redirects back to View All
        /// </summary>
        /// <param name="recipeID"></param>
        /// <returns>Redirect back to View All</returns>
        [RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult DeleteRecipe (int recipeID)
        {
            //Return variable
            ActionResult result;
            try
            {
                _recipeDAO.DeleteRecipe(recipeID);
                result = RedirectToAction("ViewAllRecipes");
            }
            catch (Exception e)
            {
                //Error occurred, return view with message
                WriteErrorToLog(e);
                TempData["Message"] = e.Data["Problem"];
                result = RedirectToAction("ViewRecipe", new {recipeID});
            }

            return result;
        }

        /// <summary>
        ///     Edit recipe basic details partial view
        /// </summary>
        /// <param name="recipeID">Id for recipe</param>
        /// <returns>partial view for recipe basic info update</returns>
        [HttpGet, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public PartialViewResult EditRecipePartial (int recipeID)
        {
            PartialViewResult response;
            try
            {
                ViewBag.Message = TempData["Message"];
                response = PartialView(new RecipePO(_recipeDAO.ReadRecipe(recipeID)));
            }
            catch (Exception e)
            {
                //Error occurred, return with message
                WriteErrorToLog(e);
                ViewBag.Message = e.Data["Problem"];
                response = PartialView(new RecipePO());
            }

            return response;
        }

        /// <summary>
        ///     Update recipe basic info, takes in basic details only
        /// </summary>
        /// <param name="recipe">recipe being updated</param>
        /// <returns>returns the get so that further updates can be made if needed.</returns>
        [HttpPost, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult EditRecipePartial (RecipePO recipe)
        {
            //Return variable
            ActionResult response;
            if (ModelState.IsValid)
                try
                {
                    _recipeDAO.UpdateRecipe(recipe);
                }
                catch (Exception e)
                {
                    //Error occurred, return with message
                    WriteErrorToLog(e);
                    TempData["Message"] = e.Data["Problem"];
                }
                finally
                {
                    //Both success and fail redirect back to GET
                    response = RedirectToAction("EditRecipePartial", new {recipeID = recipe.ID});
                }
            else //ModelState is not valid
                response = View(recipe);

            return response;
        }

        /// <summary>
        ///     Creates Implementation for RecipeID using default values
        ///     redirects to the Update implementation factory partial view
        /// </summary>
        /// <param name="recipeID"></param>
        /// <returns>redirect to update implementation factory partial</returns>
        [RoleCheck(DefaultRedirect, Admin, PowerUser)]
        public ActionResult CreateImplementationPartial (int recipeID)
        {
            //Return variable
            ActionResult response;
            //ID of implementation created
            var implementationID = default(int);
            try
            {
                implementationID =
                    _ingredientImplementationDAO.CreateIngredientImplementation(
                                                                                new IngredientImplementationPO
                                                                                    {RecipeID = recipeID});

MenuMakerPL/Views/Recipe/CreateRecipe.cshtml
@model MenuMakerPL.Models.RecipePO

@{ ViewBag.Title = "Create Recipe"; }

<h2>Create Recipe</h2>
<h3 class="text-danger">@ViewBag.Message</h3>

@using (Html.BeginForm("CreateRecipe", "Recipe"))
{
    @Html.Partial("_CreateUpdateRecipe", Model)
}

MenuMakerPL/Views/Recipe/DeleteImplementation.cshtml
@*This is an empty view to return when an Implementation is deleted.*@
@* It can probably be replaced with empty result or something*@

MenuMakerPL/Views/Recipe/EditImplementationPartial.cshtml
@model MenuMakerPL.Models.IngredientImplementationPO

@{ Layout = null; }

<h5 class="text-danger">@ViewBag.Message</h5>

<div class="container">
    <div class="row">
        <div class="form-group">
            @Html.EditorFor(model => model.ImplementationID)
            @Html.EditorFor(model => model.RecipeID)
            @Html.HiddenFor(model => model.Name)
        </div>
        <div class="form-group col-xs-3">
            @Html.LabelFor(model => model.Name)
            <div class="row">
                @Html.DropDownListFor(model => model.IngredientID, Model.IngredientDropList)
            </div>
        </div>
        <button class="btn col-xs-2" type="submit" name="button" value="Update">
            Update Ingredient
        </button>
        <div class="col-xs-1"></div>
        <button class="col-xs-2 btn btn-danger" type="submit" name="button" value="Delete"
                onclick="return ConfirmDelete('@Model.Name')">
            Delete
        </button>
    </div>
    <div class="row">
        <div class="form-group col-sm-2">
            @Html.LabelFor(model => model.Quantity)
            @Html.TextBoxFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </div>
        <div class="form-group col-sm-2">
            @Html.LabelFor(model => model.Unit)
            @Html.DisplayFor(model => model.Unit)
            @Html.ValidationMessageFor(model => model.Unit)
        </div>
        <div class="form-group col-sm-2">
            @Html.LabelFor(model => model.Price)
            @Html.DisplayFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        <div class="form-group col-sm-2">
            @Html.LabelFor(model => model.Cost)
            @Html.DisplayFor(model => model.Cost)
            @Html.ValidationMessageFor(model => model.Cost)
        </div>
    </div>
</div>

MenuMakerPL/Views/Recipe/EditImplementationPartialFactory.cshtml
@model int

@{ Layout = null; }
<script src="~/Scripts/ConfirmDelete.js"></script>
<h3 class="text-danger">@ViewBag.Message</h3>

@using (Ajax.BeginForm("EditImplementationPartial", //This is the method to post to
                       new {implementationID = Model},
                       new AjaxOptions
                       {
                           InsertionMode = InsertionMode.Replace,
                           UpdateTargetId = Model.ToString()
                       },
                       new {id = Model.ToString()}))
{
    @Html.Action("EditImplementationPartial", new {implementationID = Model}) //This is the get method
}

MenuMakerPL/Views/Recipe/EditRecipePartial.cshtml
@model MenuMakerPL.Models.RecipePO

@{ Layout = null; }
<h3 class="text-danger">@ViewBag.Message</h3>

<div class="form-group row">
    @Html.EditorFor(model => model.ID)
</div>
@Html.Partial("_CreateUpdateRecipe")

MenuMakerPL/Views/Recipe/UpdateRecipe.cshtml
@model MenuMakerPL.Models.FullRecipeVM

@{
    ViewBag.Title = "Edit Recipe";
}
<script src="~/Scripts/jquery-3.0.0.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<h2>Edit Recipe</h2>
<h3 class="text-danger">@ViewBag.Message</h3>

@using (Ajax.BeginForm("EditRecipePartial",
                       new {recipeID = Model.Recipe.ID},
                       new AjaxOptions
                       {
                           InsertionMode = InsertionMode.Replace,
                           UpdateTargetId = "Recipe"
                       }))
{
    <div id="Recipe">
        @Html.Action("EditRecipePartial", new {recipeID = Model.Recipe.ID})
    </div>
}

<br/>
<div id="Ingredients">
    @foreach (var ingredient in Model.Ingredients)
    {
        <div>
            @Html.Action("EditImplementationPartialFactory", new {implementationID = ingredient.ImplementationID})
        </div>
    }
</div>
<br/>
@Ajax.ActionLink("Add ingredient", "CreateImplementationPartial", new {recipeID = Model.Recipe.ID},
                 new AjaxOptions {UpdateTargetId = "Ingredients", InsertionMode = InsertionMode.InsertAfter},
                 new {@class = "btn btn-info"})
<br/>
<br/>
<br/>
@Html.ActionLink("Done", "ViewRecipe", new {recipeID = Model.Recipe.ID}, new {@class = "btn btn-info"})

MenuMakerPL/Views/Recipe/ViewAllRecipes.cshtml
@using MenuMakerPL.Models
@model List<MenuMakerPL.Models.RecipePO>

@{ ViewBag.Title = "Recipes"; }
<script src="~/Scripts/jquery-3.0.0.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<h2>Recipes</h2>
<h3 class="text-danger">@ViewBag.Message</h3>

<div class="container">
    <div class="row">
        <div class="col-sm-2">

            @if (((UserPO)Session["User"])?.RoleName == "Admin" ||
                 ((UserPO)Session["User"])?.RoleName == "PowerUser")
            {
                @Html.ActionLink("Create new Recipe", "CreateRecipe", "Recipe", null, new {@class = "btn btn-info"})
            }
            @*Inadequate role.*@
        </div>
    </div>
    @foreach (var recipe in Model)
    {
        <div class="row">
            <div class="col-sm-2">
                @Ajax.ActionLink("Add to Shopping List", "AddRecipeToShoppingList",
                                 "User", new {recipeID = recipe.ID}, null)
            </div>
            <div class="col-sm-2">
                @Html.DisplayFor(model => recipe.Name)
            </div>
            <div class="col-sm-4">
                @Html.DisplayFor(model => recipe.Description)
            </div>
            <div class="col-sm-2">
                @Html.ActionLink("View Details", "ViewRecipe", "Recipe", new {recipeID = recipe.ID}, null)
            </div>
        </div>
    }
</div>

MenuMakerPL/Views/Recipe/ViewRecipe.cshtml
@using MenuMakerPL.Models
@model MenuMakerPL.Models.FullRecipeVM

@{ ViewBag.Title = "Recipe Details"; }
<script src="~/Scripts/ConfirmDelete.js"></script>

<h2>@Html.DisplayFor(model => Model.Recipe.Name)</h2>
<h3 class="text-danger">@ViewBag.Message</h3>

<div class="container">
    <h3>Description</h3>
    <div class="row">
        <div class="col-sm-8">
            @Html.TextAreaFor(model => Model.Recipe.Description, new {@readonly = true})
        </div>
    </div>
    <h3>Ingredients</h3>
    @foreach (var ingredient in Model.Ingredients)
    {
        <div class="row">
            <div class="col-sm-2 col-xs-2">
                @Html.DisplayFor(model => ingredient.Quantity) @Html.DisplayFor(model => ingredient.Unit)
            </div>
            <div class="col-sm-2 col-xs-6">
                @Html.DisplayFor(model => ingredient.Name)
            </div>
            <div class="col-sm-1 col-xs-2">
                @Html.DisplayFor(model => ingredient.Cost)
            </div>
        </div>
    }
    <h4>Total Cost:</h4>
    <div class="row">
        <div class="col-sm-6">
            @Html.DisplayFor(model => model.Cost)
        </div>
    </div>
    <h3>Directions</h3>
    <div class="row">
        <div class="col-sm-8">
            @Html.TextAreaFor(model => Model.Recipe.Directions, new {@readonly = true})
        </div>
    </div>
    @if (((UserPO)Session["User"])?.RoleName == "Admin" ||
         ((UserPO)Session["User"])?.RoleName == "PowerUser")
    {
        <div class="row">
            <div class="col-xs-2">
                @Html.ActionLink("Update", "UpdateRecipe", "Recipe", new {recipeID = Model.Recipe.ID},
                                 new {@class = "btn btn-warning"})
            </div>
            <div class="col-xs-4"></div>
            <div class="col-xs-2">
                @Html.ActionLink("Delete", "DeleteRecipe", "Recipe", new {recipeID = Model.Recipe.ID},
                                 new {@class = "btn btn-danger", onclick = "return ConfirmDelete('" + Model.Recipe.Name + "')"})
            </div>
        </div>
    }
    @*Inadequate role.*@
</div>

MenuMakerPL/Views/Recipe/_CreateUpdateRecipe.cshtml
@model MenuMakerPL.Models.RecipePO

<div class="container">
    <div class="form-group row">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
        <div class="row">
            @Html.TextAreaFor(model => model.Description)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.Directions)
        @Html.ValidationMessageFor(model => model.Directions)
        <div class="row">
            @Html.TextAreaFor(model => model.Directions)
        </div>
    </div>
</div>

<button type="submit" class="btn">Submit</button>