MenuMakerPL/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using MenuMakerDAL;
using MenuMakerPL.Controllers.ActionFilters;
using MenuMakerPL.Models;

namespace MenuMakerPL.Controllers
{
    /// <summary>
    ///     Controller for all Ingredient details needs. Must be a registered user to view
    /// </summary>
    [RoleCheck(DefaultRedirect, StandardUser, PowerUser, Admin)]
    public class IngredientsController : MMController
    {
        // ReSharper disable once FieldCanBeMadeReadOnly.Local
        //Override DAO to clarify its type
        private IngredientsDAO _dataAccess;

        public IngredientsController ()
        {
            var connection = ConfigurationManager.ConnectionStrings["MenuMaker"].ConnectionString;
            _dataAccess = new IngredientsDAO(connection);
        }

        /// <summary>
        ///     Sets landing page to View All
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index ()
        {
            return RedirectToAction("ViewAllIngredients");
        }

        /// <summary>
        ///     Create ingredient page, must be at least PowerUser to view
        /// </summary>
        /// <returns></returns>
        [HttpGet, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult CreateIngredient ()
        {
            //Return variable
            ActionResult result = View();

            return result;
        }

        /// <summary>
        ///     Create ingredient POST method, must be at least PowerUser to use
        /// </summary>
        /// <param name="ingredientPOToCreate">ingredient to create</param>
        /// <returns>Returns user to View All</returns>
        [HttpPost, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult CreateIngredient (IngredientPO ingredientPOToCreate)
        {
            //Return variable
            ActionResult result;
            if (ModelState.IsValid)
                try
                {
                    _dataAccess.CreateIngredient(ingredientPOToCreate);
                    result = RedirectToAction("ViewAllIngredients");
                }
                catch (Exception e)
                {
                    //Problem occurred, return to user with message.
                    WriteErrorToLog(e);
                    ViewBag.Message = e.Data["Problem"];
                    result = View(ingredientPOToCreate);
                }
            else //ModelState not valid, return back to user.
                result = View(ingredientPOToCreate);

            return result;
        }

        /// <summary>
        ///     View All page, uses controller's access for role check
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ViewAllIngredients ()
        {
            //Return Variable
            ActionResult result;
            ViewBag.Message = TempData["Message"];
            try
            {
                var ingredients = new List<IngredientPO>();
                //Convert objects to PO for viewing
                foreach (var ingredient in _dataAccess.ReadAllIngredients())
                    ingredients.Add(new IngredientPO(ingredient));
                result = View(ingredients);
            }
            catch (Exception e)
            {
                //Problem occurred, return view with message.
                WriteErrorToLog(e);
                ViewBag.Message = e.Data["Problem"];
                result = View(new List<IngredientPO>());
            }

            return result;
        }

        /// <summary>
        ///     Get call that gets ingredient object fresh from DB
        /// </summary>
        /// <param name="ingredientID">Primary key of the Ingredient in the DB</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ViewSingleIngredient (int ingredientID)
        {
            //Return variable
            ActionResult result;
            try
            {
                //Get ingredient to view and convert to PO
                var ingredientPO = new IngredientPO(_dataAccess.ReadIngredient(ingredientID));
                result = View(ingredientPO);
                ViewBag.Message = TempData["Message"];
            }
            catch (Exception e)
            {
                //Problem occurred, return view to user with message
                WriteErrorToLog(e);
                TempData["Message"] = e.Data["Problem"];
                result = RedirectToAction("ViewAllIngredients");
            }

            return result;
        }

        /// <summary>
        ///     Update Ingredient page, only accessible to at least PowerUsers
        /// </summary>
        /// <param name="ingredientId">ID of ingredient to update</param>
        /// <returns></returns>
        [HttpGet, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult UpdateIngredient (int ingredientId)
        {
            //Return variable
            ActionResult result;
            try
            {
                //Get ingredient and convert to PO for View
                var ingredientPO = new IngredientPO(_dataAccess.ReadIngredient(ingredientId));
                result = View(ingredientPO);
            }
            catch (Exception e)
            {
                //Problem occurred, return view to user with message
                WriteErrorToLog(e);
                ViewBag.Message = e.Data["Problem"];
                result = View(new IngredientPO());
            }

            return result;
        }

        /// <summary>
        ///     Collect form and update ingredient, returns to View Single Ingredient
        /// </summary>
        /// <param name="ingredient"></param>
        /// <returns>Single Ingredient Page</returns>
        [HttpPost, RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult UpdateIngredient (IngredientPO ingredient)
        {
            //Return Variable
            ActionResult result;
            if (ModelState.IsValid)
                try
                {
                    _dataAccess.UpdateIngredient(ingredient);
                    result = RedirectToAction("ViewSingleIngredient", new {ingredientID = ingredient.IngredientID});
                }
                catch (Exception e)
                {
                    //Error occurred, return to user with message.
                    WriteErrorToLog(e);
                    ViewBag.Message = e.Data["Problem"];
                    result = View(ingredient);
                }
            else //ModelState not valid, return to user
                result = View(ingredient);

            return result;
        }

        /// <summary>
        ///     Delete ingredient by ID, returns to View All
        /// </summary>
        /// <param name="ingredientID">id of ingredient to delete</param>
        /// <returns></returns>
        [RoleCheck(DefaultRedirect, PowerUser, Admin)]
        public ActionResult DeleteIngredient (int ingredientID)
        {
            ActionResult result;
            try
            {
                _dataAccess.DeleteIngredient(ingredientID);
                result = RedirectToAction("ViewAllIngredients");
            }
            catch (Exception e)
            {
                //Error occurred, return back to details with message
                WriteErrorToLog(e);
                TempData["Message"] = e.Data["Problem"];
                result = RedirectToAction("ViewSingleIngredient", new {ingredientID});
            }

            return result;
        }
    }
}

MenuMakerPL/Views/Ingredients/CreateIngredient.cshtml
@model MenuMakerPL.Models.IngredientPO

@{ ViewBag.Title = "Create Ingredient"; }

<h1>Create Ingredient</h1>
<h3 class="text-danger">@ViewBag.Message</h3>

@using (Html.BeginForm("CreateIngredient", "Ingredients"))
{
    @Html.Partial("_CreateUpdateIngredient")
}

MenuMakerPL/Views/Ingredients/UpdateIngredient.cshtml
@model MenuMakerPL.Models.IngredientPO

@{ ViewBag.Title = "Edit Ingredient"; }

<h1>Edit Ingredient</h1>

@using (Html.BeginForm("UpdateIngredient", "Ingredients"))
{
    <div class="form-group">
        @Html.EditorFor(model => model.IngredientID)
    </div>
    @Html.Partial("_CreateUpdateIngredient", Model)
}

MenuMakerPL/Views/Ingredients/ViewAllIngredients.cshtml
@using MenuMakerPL.Models
@model List<MenuMakerPL.Models.IngredientPO>

@{ ViewBag.Title = "Ingredients"; }

<h2>Ingredients</h2>
<h3 class="text-danger">@ViewBag.Message</h3>
<div class="container" summary="List of all ingredients with unit type.">
    <div class="row">
        @if (((UserPO)Session["User"])?.RoleName == "Admin" ||
             ((UserPO)Session["User"])?.RoleName == "PowerUser")
        {
            @Html.ActionLink("Create new Ingredient", "CreateIngredient", "Ingredients", null,
                             new {@class = "btn btn-info"})
        }
        @*Inadequate role.*@
    </div>
    <div class="row">
        <div class="col-xs-3">@Html.LabelFor(model => model[0].Name)</div>
        <div class="col-xs-3">@Html.LabelFor(model => model[0].Unit)</div>
        <div class="col-xs-3">@Html.LabelFor(model => model[0].Price)</div>
    </div>

    @foreach (var ingredient in Model)
    {
        <div class="row">
            @Html.Partial("_SingleIngredient", ingredient)
            @Html.ActionLink("View Details", "ViewSingleIngredient", "Ingredients",
                             new {ingredientID = ingredient.IngredientID}, null)
        </div>
    }
</div>

MenuMakerPL/Views/Ingredients/ViewSingleIngredient.cshtml
@using MenuMakerPL.Models
@model MenuMakerPL.Models.IngredientPO
<script src="~/Scripts/ConfirmDelete.js"></script>

@{ ViewBag.Title = "Create Ingredient"; }
<h3 class="text-danger">@ViewBag.Message</h3>

<div class="container">
    <div class="row">
        <div class="col-xs-3">@Html.LabelFor(model => model.Name)</div>
        <div class="col-xs-3">@Html.LabelFor(model => model.Unit)</div>
        <div class="col-xs-3">@Html.LabelFor(model => model.Price)</div>
    </div>
    <div class="row">
        @Html.Partial("_SingleIngredient", Model)
    </div>
    <div class="row">
        @if (((UserPO)Session["User"])?.RoleName == "Admin" ||
             ((UserPO)Session["User"])?.RoleName == "PowerUser")
        {
            @Html.ActionLink("Edit", "UpdateIngredient", "Ingredients", new {ingredientID = Model.IngredientID},
                             new {@class = "btn btn-warning col-xs-2"})
            <div class="col-xs-4"></div>
            @Html.ActionLink("Delete", "DeleteIngredient", "Ingredients", new {ingredientID = Model.IngredientID},
                             new {@class = "btn btn-danger col-xs-2", onclick = "return ConfirmDelete('" + Model.Name + "')"})
        }
        @*Inadequate role.*@
    </div>
</div>

MenuMakerPL/Views/Ingredients/_CreateUpdateIngredient.cshtml
@model MenuMakerPL.Models.IngredientPO
<div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Unit)
    @Html.TextBoxFor(model => model.Unit)
    @Html.ValidationMessageFor(model => model.Unit)
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Price)
    @Html.TextBoxFor(model => model.Price)
    @Html.ValidationMessageFor(model => model.Price)
</div>
<button type="submit" class="btn">Submit</button>

MenuMakerPL/Views/Ingredients/_SingleIngredient.cshtml
@model MenuMakerPL.Models.IngredientPO

<div class="col-xs-3">@Html.DisplayFor(model => model.Name)</div>
<div class="col-xs-3">@Html.DisplayFor(model => model.Unit)</div>
<div class="col-xs-3">@Html.DisplayFor(model => model.Price)</div>